/** Tenant-wise CSV templates from profiling bulk-upload module */

export type StudentCsvField = {
  key: string;
  label: string;
  required: boolean;
  type?: 'text' | 'email' | 'mobile' | 'year' | 'date';
};

export const TENANT_CSV_TEMPLATES: Record<string, StudentCsvField[]> = {
  UNIVERSITY: [
    { key: 'registration_or_user_id', label: 'Registration/User ID', required: true },
    { key: 'full_name', label: 'Full Name', required: true },
    { key: 'email', label: 'Email', required: true, type: 'email' },
    { key: 'mobile', label: 'Mobile', required: true, type: 'mobile' },
    { key: 'gender', label: 'Gender', required: true },
    { key: 'date_of_birth', label: 'Date of Birth', required: true, type: 'date' },
    { key: 'academic_year', label: 'Academic Year', required: true },
    { key: 'expected_passout_year', label: 'Expected Passout Year', required: true },
    { key: 'onboarding_date', label: 'Onboarding Date', required: true, type: 'date' },
    { key: 'department_branch_specialization', label: 'Department/Branch/Specialization', required: true },
    { key: 'current_year_of_study', label: 'Current Year of Study', required: true },
  ],
  COLLEGE: [
    { key: 'registration_or_user_id', label: 'Registration/User ID', required: true },
    { key: 'full_name', label: 'Full Name', required: true },
    { key: 'email', label: 'Email', required: true, type: 'email' },
    { key: 'mobile', label: 'Mobile', required: true, type: 'mobile' },
    { key: 'gender', label: 'Gender', required: true },
    { key: 'date_of_birth', label: 'Date of Birth', required: true, type: 'date' },
    { key: 'academic_year', label: 'Academic Year', required: true },
    { key: 'expected_passout_year', label: 'Expected Passout Year', required: true },
    { key: 'onboarding_date', label: 'Onboarding Date', required: true, type: 'date' },
    { key: 'department_branch_specialization', label: 'Department/Branch/Specialization', required: true },
    { key: 'current_year_of_study', label: 'Current Year of Study', required: true },
  ],
  CORPORATE: [
    { key: 'employee_id', label: 'Employee ID', required: true },
    { key: 'full_name', label: 'Full Name', required: true },
    { key: 'corporate_email', label: 'Corporate Email', required: true, type: 'email' },
    { key: 'mobile_number', label: 'Mobile Number', required: true, type: 'mobile' },
    { key: 'gender', label: 'Gender', required: true },
    { key: 'date_of_birth', label: 'Date of Birth', required: true, type: 'date' },
    { key: 'business_unit', label: 'Business Unit', required: true },
    { key: 'department', label: 'Department', required: true },
    { key: 'team', label: 'Team', required: false },
    { key: 'designation', label: 'Designation', required: true },
    { key: 'reporting_manager', label: 'Reporting Manager', required: false },
    { key: 'office_location', label: 'Office Location', required: false },
    { key: 'employment_type', label: 'Employment Type', required: true },
    { key: 'employment_status', label: 'Employment Status', required: true },
    { key: 'employee_grade', label: 'Employee Grade', required: false },
    { key: 'date_of_joining', label: 'Date of Joining', required: true, type: 'date' },
    { key: 'current_role', label: 'Current Role', required: true },
    { key: 'assigned_learning_path', label: 'Assigned Learning Path', required: false },
  ],
  SKILL_ACADEMY: [
    { key: 'learner_id', label: 'Learner ID', required: true },
    { key: 'full_name', label: 'Full Name', required: true },
    { key: 'email', label: 'Email', required: true, type: 'email' },
    { key: 'mobile_number', label: 'Mobile Number', required: true, type: 'mobile' },
    { key: 'gender', label: 'Gender', required: true },
    { key: 'date_of_birth', label: 'Date of Birth', required: true, type: 'date' },
    { key: 'skill_domain', label: 'Skill Domain', required: true },
    { key: 'program', label: 'Program', required: true },
    { key: 'specialization', label: 'Specialization', required: false },
    { key: 'training_cohort', label: 'Training Cohort', required: true },
    { key: 'batch', label: 'Batch', required: true },
    { key: 'practical_lab_group', label: 'Practical/Lab Group', required: false },
    { key: 'enrollment_date', label: 'Enrollment Date', required: true, type: 'date' },
    { key: 'expected_completion_date', label: 'Expected Completion Date', required: true, type: 'date' },
    { key: 'learner_status', label: 'Learner Status', required: true },
    { key: 'highest_qualification', label: 'Highest Qualification', required: false },
    { key: 'technical_skills', label: 'Technical Skills', required: false },
    { key: 'skill_proficiency_level', label: 'Skill Proficiency Level', required: false },
  ],
  BOOTCAMP: [
    { key: 'learner_id', label: 'Learner ID', required: true },
    { key: 'full_name', label: 'Full Name', required: true },
    { key: 'email', label: 'Email', required: true, type: 'email' },
    { key: 'mobile_number', label: 'Mobile Number', required: true, type: 'mobile' },
    { key: 'gender', label: 'Gender', required: true },
    { key: 'date_of_birth', label: 'Date of Birth', required: true, type: 'date' },
    { key: 'domain', label: 'Domain', required: true },
    { key: 'program', label: 'Program', required: true },
    { key: 'specialization', label: 'Specialization', required: false },
    { key: 'cohort', label: 'Cohort', required: true },
    { key: 'batch', label: 'Batch', required: true },
    { key: 'enrollment_date', label: 'Enrollment Date', required: true, type: 'date' },
    { key: 'expected_completion_date', label: 'Expected Completion Date', required: true, type: 'date' },
    { key: 'learner_status', label: 'Learner Status', required: true },
    { key: 'highest_qualification', label: 'Highest Qualification', required: false },
    { key: 'skill_names', label: 'Skill Names', required: false },
    { key: 'skill_categories', label: 'Skill Categories', required: false },
    { key: 'skill_proficiency', label: 'Skill Proficiency', required: false },
  ],
  NGO: [
    { key: 'learner_external_id', label: 'Learner External ID', required: true },
    { key: 'full_name', label: 'Full Name', required: true },
    { key: 'mobile_number', label: 'Mobile Number', required: true, type: 'mobile' },
    { key: 'email', label: 'Email', required: false, type: 'email' },
    { key: 'gender', label: 'Gender', required: true },
    { key: 'date_of_birth', label: 'Date of Birth', required: true, type: 'date' },
    { key: 'state', label: 'State', required: true },
    { key: 'district', label: 'District', required: true },
    { key: 'centre_name', label: 'Centre Name', required: true },
    { key: 'project_name', label: 'Project Name', required: true },
    { key: 'programme_name', label: 'Programme Name', required: true },
    { key: 'batch_name', label: 'Batch Name', required: true },
    { key: 'highest_education', label: 'Highest Education', required: false },
    { key: 'employment_status', label: 'Employment Status', required: false },
    { key: 'family_income_band', label: 'Family Income Band', required: false },
    { key: 'village_town', label: 'Village/Town', required: false },
    { key: 'preferred_language', label: 'Preferred Language', required: false },
    { key: 'internet_access', label: 'Internet Access', required: false },
    { key: 'device_access', label: 'Device Access', required: false },
  ],
  GOVERNMENT: [
    { key: 'employee_id', label: 'Employee ID', required: true },
    { key: 'government_employee_code', label: 'Government Employee Code', required: true },
    { key: 'full_name', label: 'Full Name', required: true },
    { key: 'gender', label: 'Gender', required: true },
    { key: 'date_of_birth', label: 'Date of Birth', required: true, type: 'date' },
    { key: 'official_email', label: 'Official Email', required: true, type: 'email' },
    { key: 'department', label: 'Department', required: true },
    { key: 'designation', label: 'Designation', required: true },
    { key: 'cadre', label: 'Cadre', required: false },
    { key: 'joining_date', label: 'Joining Date', required: true, type: 'date' },
    { key: 'district', label: 'District', required: true },
    { key: 'state', label: 'State', required: true },
  ],
};

export const STUDENT_CSV_FIELDS = TENANT_CSV_TEMPLATES.UNIVERSITY;

export function getTemplateForTenantType(tenantType: string): StudentCsvField[] {
  return TENANT_CSV_TEMPLATES[tenantType] ?? TENANT_CSV_TEMPLATES.UNIVERSITY;
}
